export const cardsData = [
  {
    id: 1,
    src: "/images/dragon1.png",
    alt: "Image of model dragon 1",
    name: "Dragon White",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, beatae!",
  },
  {
    id: 2,
    src: "/images/dragon2.png",
    alt: "Image of model dragon 2",
    name: "Dragon",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, beatae!",
  },
  {
    id: 3,
    src: "/images/spartan.png",
    alt: "Image of model spartan",
    name: "Spartan Fighter",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, beatae!",
  },
  {
    id: 4,
    src: "/images/woman.png",
    alt: "Image of model woman",
    name: "Cyber Women",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, beatae!",
  },
];

export const roadmapData = [
  {
    id: 1,
    src: "/images/img1.jpg",
    alt: "PlaceHolder Image",
    heading: "Lorem Ipsum",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit distinctio qui.",
  },
  {
    id: 2,
    src: "/images/img1.jpg",
    alt: "PlaceHolder Image",
    heading: "Lorem Ipsum",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit distinctio qui.",
  },
  {
    id: 3,
    src: "/images/img1.jpg",
    alt: "PlaceHolder Image",
    heading: "Lorem Ipsum",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit distinctio qui.",
  },
  {
    id: 4,
    src: "/images/img1.jpg",
    alt: "PlaceHolder Image",
    heading: "Lorem Ipsum",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit distinctio qui.",
  },
  {
    id: 5,
    src: "/images/img1.jpg",
    alt: "PlaceHolder Image",
    heading: "Lorem Ipsum",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit distinctio qui.",
  },
  {
    id: 6,
    src: "/images/img1.jpg",
    alt: "PlaceHolder Image",
    heading: "Lorem Ipsum",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit distinctio qui.",
  },
  {
    id: 7,
    src: "/images/img1.jpg",
    alt: "PlaceHolder Image",
    heading: "Lorem Ipsum",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit distinctio qui.",
  },
  {
    id: 8,
    src: "/images/img1.jpg",
    alt: "PlaceHolder Image",
    heading: "Lorem Ipsum",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit distinctio qui.",
  },
  {
    id: 9,
    src: "/images/img1.jpg",
    alt: "PlaceHolder Image",
    heading: "Lorem Ipsum",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit distinctio qui.",
  },
  {
    id: 10,
    src: "/images/img1.jpg",
    alt: "PlaceHolder Image",
    heading: "Lorem Ipsum",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit distinctio qui.",
  },
];
