import "@/app/ui/globals.css";
import { inter } from "@/app/ui/fonts";

export const metadata = {
  title: "3D Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>{children}</body>
    </html>
  );
}
